name: line

batch_size: 128
num_workers: 0  # 0 means start no additional processes, but use the main process. For small in-memory dataset, this makes sense

num_points: 1000
noise: 0.01
slope: -0.5
intercept: 1.0