defaults:
  - algorithm: mlp
  - dataset: on_disk
  - platform: bwuni_dev_gpu_4_copy_dataset
  - _self_


epochs: 500
device: cuda
name: exp_1_local_on_disk
group_name: local
visualize: True
wandb: True  # Change this to True to enable WandB logging!
seed: 100

hydra:
  # don't need to specify mode: MULTIRUN, because it's in the platform config
  sweeper:
    params:
      seed: 0