defaults:
  - algorithm: mlp
  - dataset: sine
  - platform: local
  - _self_


epochs: 500
device: cuda
name: exp_1_local_sine
group_name: local
visualize: True
wandb: False  # Change this to True to enable WandB logging!
seed: 100
