defaults:
  - algorithm: mlp
  - dataset: sine
  - platform: local
  - _self_

# overwrite a specific value of the default config
algorithm:
  activation_function: relu

epochs: 500
device: cuda
name: exp_2_local_relu
group_name: local
visualize: True
wandb: True
seed: 100
