defaults:
  - algorithm: mlp
  - dataset: line
  - platform: bwuni_all_gpus
  - _self_


epochs: 300
device: cuda
name: exp_5_bwuni_line
group_name: bwuni
visualize: True
wandb: True
seed: 100

hydra:
  # don't need to specify mode: MULTIRUN, because it's in the platform config
  sweeper:
    params:
      seed: 0, 1, 2, 3  # starts 4 jobs in parallel

